//! Glade wire codec (GLP-0005, P0.S4): IR-driven CBOR codec over generated
//! native structs for the glade framing protocol (`taut/ir/glade.taut.py`).
//!
//! `cbor.rs` and `generated.rs` are REGENERATED by
//! `python -m taut.corpus.glade_build`, run in taut's checkout at the
//! commit the workspace lock pins — do not edit them by hand; each names the
//! taut tag it came from. The conformance tests below prove this crate
//! reproduces taut's Python-authored golden corpus byte-for-byte;
//! parity == correctness, and the same corpus pins the TypeScript codec
//! (browser-folds premise). Decode is taut's fail-closed codec: `try_decode`,
//! each enum's `from_wire` and each message's `from_cbor` return a
//! `DecodeError` where the legacy codec panicked, and decode is bounded
//! (TautCheckedDecode.md §7, CD-G1 and CD-G2). `frame.rs` is written by hand:
//! a frame's size limit (CD-G3).

// The runtime (`cbor.rs`) uses `core` and `alloc` only.
extern crate alloc;

// `cbor.rs` and `generated.rs` are taut's output, formatted as taut writes
// them, so rustfmt leaves them alone.
#[rustfmt::skip]
pub mod cbor;
pub mod frame;
#[rustfmt::skip]
pub mod generated;
pub mod swmr;

#[cfg(test)]
mod codec_tests {
    use crate::cbor;
    use crate::generated::{self, Op, Shape, VECTORS};
    use crate::swmr::{decode_swmr, encode_swmr, SwmrAction, SwmrPayloadError};

    fn hex_to_bytes(h: &str) -> Vec<u8> {
        (0..h.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&h[i..i + 2], 16).unwrap())
            .collect()
    }
    fn bytes_to_hex(b: &[u8]) -> String {
        b.iter().map(|x| format!("{:02x}", x)).collect()
    }

    /// The vector named `name`, decoded as an `Op`.
    fn op_vector(name: &str) -> Op {
        let entry = VECTORS.iter().find(|(n, _, _)| *n == name).unwrap();
        Op::from_cbor(&cbor::try_decode(&hex_to_bytes(entry.2)).unwrap()).unwrap()
    }

    /// The CBOR substrate alone round-trips every vector (decode->encode).
    #[test]
    fn cbor_substrate_roundtrips_corpus() {
        for (name, _msg, hex) in VECTORS {
            let decoded = cbor::try_decode(&hex_to_bytes(hex)).unwrap();
            let re = bytes_to_hex(&cbor::encode(&decoded));
            assert_eq!(&re, hex, "cbor substrate mismatch for {}", name);
        }
    }

    /// The IR codec reproduces every golden vector byte-for-byte via the typed
    /// structs: bytes -> native struct -> bytes.
    #[test]
    fn ir_codec_reproduces_corpus_byte_for_byte() {
        assert!(!VECTORS.is_empty(), "no vectors generated");
        for (name, message, hex) in VECTORS {
            let re = generated::roundtrip(message, &hex_to_bytes(hex)).unwrap();
            assert_eq!(&bytes_to_hex(&re), hex, "IR codec mismatch for {}", name);
        }
    }

    /// Spot-check a typed decode: the op envelope's identity + fold fields.
    #[test]
    fn op_envelope_decodes_typed() {
        let op = op_vector("edge/op-chain");
        assert_eq!(op.seq, 5);
        assert_eq!(op.prev.as_ref().unwrap().len(), 32); // per-origin chain hash (GQ-9)
        assert_eq!(op.shape, Shape::Log);
        assert!(!op.refs.is_empty()); // causal refs
    }

    #[test]
    fn swmr_shape_and_action_envelope_are_frozen() {
        assert_eq!(Shape::Swmr.wire(), 3);
        for (action, tag) in [
            (SwmrAction::Snapshot, 0_u8),
            (SwmrAction::Delta, 1_u8),
            (SwmrAction::Reset, 2_u8),
        ] {
            let encoded = encode_swmr(action, b"body");
            assert_eq!(&encoded[..2], &[1, tag]);
            let decoded = decode_swmr(&encoded).unwrap();
            assert_eq!(decoded.action, action);
            assert_eq!(decoded.body, b"body");
        }

        let op = op_vector("edge/op-swmr");
        assert_eq!(op.shape, Shape::Swmr);
        assert_eq!(
            decode_swmr(&op.payload).unwrap().action,
            SwmrAction::Snapshot
        );
    }

    #[test]
    fn crdt_shape_is_additive_and_payload_opaque() {
        assert_eq!(Shape::Crdt.wire(), 4);
        let op = op_vector("edge/op-crdt");
        assert_eq!(op.shape, Shape::Crdt);
        assert_eq!(op.payload, br#"{"kind":"insert"}"#);
    }

    #[test]
    fn malformed_swmr_action_envelopes_fail_closed() {
        assert_eq!(decode_swmr(&[]), Err(SwmrPayloadError::TooShort));
        assert_eq!(decode_swmr(&[1]), Err(SwmrPayloadError::TooShort));
        assert_eq!(
            decode_swmr(&[2, 0]),
            Err(SwmrPayloadError::UnsupportedVersion(2))
        );
        assert_eq!(
            decode_swmr(&[1, 3]),
            Err(SwmrPayloadError::UnsupportedAction(3))
        );
    }
}

// F12's and F15's refusals, from taut's fail-closed codec, where the legacy
// codec panicked or overflowed its stack (CD-G1, CD-G2): these tests were
// `checked.rs`'s and `wellformed.rs`'s, which went with the legacy codec. A
// braced module, so the condition encloses the whole section.
#[cfg(test)]
mod refusal_tests {
    use crate::cbor::{self, Cbor, DecodeError, MapKey, DEFAULT_MAX_DEPTH};
    use crate::generated::{Error, ErrorCode, FrameType, Op, Ops, Priority, Shape, VECTORS};

    fn hex(h: &str) -> Vec<u8> {
        let byte = |i| u8::from_str_radix(&h[i..i + 2], 16).unwrap();
        (0..h.len()).step_by(2).map(byte).collect()
    }

    /// `levels` arrays, or maps, each the one item of the one around it, the
    /// innermost empty.
    fn nested(levels: usize, map: bool) -> Vec<u8> {
        let (open, empty): (&[u8], u8) = if map {
            (&[0xa1, 0x00], 0xa0)
        } else {
            (&[0x81], 0x80)
        };
        let mut bytes = open.repeat(levels - 1);
        bytes.push(empty);
        bytes
    }

    /// A message's map with the value at `key` replaced by the int `value`.
    fn with(mut message: Cbor, key: i64, value: i64) -> Cbor {
        if let Cbor::Map(entries) = &mut message {
            for (k, v) in entries.iter_mut() {
                if *k == key {
                    *v = Cbor::Int(value);
                }
            }
        }
        message
    }

    /// F15: the legacy decode recursed once a level, with no limit, so a
    /// frame nested 100,000 deep, 100 KB, overflowed the stack of the thread
    /// that decoded it, which aborts the process. `try_decode` refuses arrays
    /// or maps nested deeper than 32, glade's F15 bound and the codec's
    /// default, as `TooDeep`, and decodes them nested 32 deep.
    #[test]
    fn nesting_deeper_than_32_is_too_deep_not_an_abort() {
        assert_eq!(DEFAULT_MAX_DEPTH, 32);
        let too_deep = Err(DecodeError::TooDeep { limit: 32 });
        for map in [false, true] {
            assert_eq!(
                cbor::try_decode(&nested(100_000, map)),
                too_deep,
                "map: {map}"
            );
            assert_eq!(cbor::try_decode(&nested(33, map)), too_deep, "map: {map}");
            let deepest = nested(32, map);
            let decoded = cbor::try_decode(&deepest).unwrap();
            assert_eq!(cbor::encode(&decoded), deepest, "map: {map}");
        }
    }

    /// F15: the legacy decode indexed past the end of truncated bytes, and
    /// panicked. Each golden vector decodes, and each proper prefix of one,
    /// the empty one too, is `Truncated`. So is a length or a count that
    /// claims 2^64 - 1 bytes or items, and a float short of its bytes.
    #[test]
    fn truncated_bytes_are_truncated_not_a_panic() {
        for (name, _, vector) in VECTORS {
            let bytes = hex(vector);
            assert!(cbor::try_decode(&bytes).is_ok(), "{name}");
            for cut in 0..bytes.len() {
                let refused = cbor::try_decode(&bytes[..cut]);
                assert_eq!(refused, Err(DecodeError::Truncated), "{name} cut at {cut}");
            }
        }
        // Bytes, text, an array and a map, each claiming 2^64 - 1.
        for initial in [0x5b, 0x7b, 0x9b, 0xbb] {
            let claim = [&[initial][..], &[0xff; 8]].concat();
            let refused = cbor::try_decode(&claim);
            assert_eq!(refused, Err(DecodeError::Truncated), "{initial:#04x}");
        }
        let half_a_double = [0xfb, 0x3f, 0xf8, 0x00, 0x00];
        assert_eq!(
            cbor::try_decode(&half_a_double),
            Err(DecodeError::Truncated)
        );
    }

    /// F15: the legacy decode panicked on CBOR outside the wire's subset.
    /// Each such item is refused with its `DecodeError`, at the top or inside
    /// a message: a tag, an indefinite or reserved length, a break, a simple
    /// value other than false, true, null and the three floats, text that is
    /// not UTF-8, a map key that is not an int, and bytes after the item. So
    /// is what the hand-written pre-check took and the codec refuses (CD-G2):
    /// a non-canonical int, a negative or a repeated map key, and an int
    /// beyond `i64`. Each kind of item the subset takes decodes.
    #[test]
    fn malformed_bytes_are_refused_with_their_decode_error_not_a_panic() {
        use DecodeError::{
            DuplicateMapKey, IntOverflow, InvalidUtf8, NegativeMapKey, NonCanonicalInt,
            NonIntegerMapKey, TrailingBytes, UnsupportedInfo, UnsupportedMajor,
        };
        let refused: &[(&[u8], DecodeError)] = &[
            (&[0xc0, 0x00], UnsupportedMajor(6)),
            (&[0xa1, 0x01, 0x81, 0xc1, 0x00], UnsupportedMajor(6)),
            (&[0x9f, 0xff], UnsupportedInfo(31)),
            (&[0x5f, 0xff], UnsupportedInfo(31)),
            (&[0x1c], UnsupportedInfo(28)),
            (&[0xff], UnsupportedInfo(31)),
            (&[0xe0], UnsupportedInfo(0)),
            (&[0xf7], UnsupportedInfo(23)),
            (&[0xf8, 0x20], UnsupportedInfo(24)),
            (&[0x62, 0xc3, 0x28], InvalidUtf8),
            (&[0xa1, 0x61, 0x61, 0x00], NonIntegerMapKey),
            (&[0xa1, 0xf6, 0x00], NonIntegerMapKey),
            (&[0xa1, 0x80, 0x00], NonIntegerMapKey),
            (&[0x00, 0x00], TrailingBytes),
            (&[0x18, 0x01], NonCanonicalInt(1)),
            (&[0xa1, 0x19, 0x00, 0x01, 0x00], NonCanonicalInt(1)),
            (&[0xa1, 0x20, 0x00], NegativeMapKey(-1)),
            (
                &[0xa2, 0x01, 0x00, 0x01, 0x00],
                DuplicateMapKey(MapKey::Int(1)),
            ),
            (&[0x1b, 0x80, 0, 0, 0, 0, 0, 0, 0], IntOverflow),
            (&[0x3b, 0x80, 0, 0, 0, 0, 0, 0, 0], IntOverflow),
        ];
        for (bytes, why) in refused {
            assert_eq!(cbor::try_decode(bytes).as_ref(), Err(why), "{bytes:02x?}");
        }
        let taken: &[(&[u8], Cbor)] = &[
            (&[0xf4], Cbor::Bool(false)),
            (&[0xf5], Cbor::Bool(true)),
            (&[0xf6], Cbor::Null),
            (&[0xf9, 0x3e, 0x00], Cbor::Float(1.5)),
            (&[0xfa, 0x3f, 0xc0, 0x00, 0x00], Cbor::Float(1.5)),
            (
                &[0xfb, 0x3f, 0xf8, 0, 0, 0, 0, 0, 0x01],
                Cbor::Float(1.5 + f64::EPSILON),
            ),
            (
                &[0x3b, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff],
                Cbor::Int(i64::MIN),
            ),
            (&[0x40], Cbor::Bytes(vec![])),
            (&[0x60], Cbor::Text(String::new())),
            (&[0x80], Cbor::Array(vec![])),
            (
                &[0xa2, 0x00, 0x61, 0x61, 0x19, 0x01, 0x00, 0x42, 0x00, 0x01],
                Cbor::Map(vec![
                    (0, Cbor::Text("a".into())),
                    (256, Cbor::Bytes(vec![0, 1])),
                ]),
            ),
        ];
        for (bytes, value) in taken {
            assert_eq!(cbor::try_decode(bytes).as_ref(), Ok(value), "{bytes:02x?}");
        }
    }

    /// F12: a value its enum does not name is `UnknownEnum`, naming the enum
    /// and the value, where the legacy `from_wire` panicked and ended the
    /// task that read the frame: past each end of a frame type, an op's
    /// shape, a batch's priority and an error's code. The last value each
    /// names is taken.
    #[test]
    fn a_value_its_enum_does_not_name_is_unknown_not_a_panic() {
        let unknown =
            |enum_name: &'static str, value: i64| DecodeError::UnknownEnum { enum_name, value };
        let past = |last: i64| [-1, last + 1, i64::MIN, i64::MAX];
        assert_eq!(FrameType::from_wire(14), Ok(FrameType::NodeWelcome));
        for v in past(14) {
            assert_eq!(FrameType::from_wire(v), Err(unknown("FrameType", v)));
        }
        assert_eq!(Shape::from_wire(4), Ok(Shape::Crdt));
        for v in past(4) {
            assert_eq!(Shape::from_wire(v), Err(unknown("Shape", v)));
        }
        assert_eq!(Priority::from_wire(2), Ok(Priority::Bulk));
        for v in past(2) {
            assert_eq!(Priority::from_wire(v), Err(unknown("Priority", v)));
        }
        assert_eq!(ErrorCode::from_wire(6), Ok(ErrorCode::Internal));
        for v in past(6) {
            assert_eq!(ErrorCode::from_wire(v), Err(unknown("ErrorCode", v)));
        }
    }

    /// F12, inside a message: an `Ops` frame whose op's shape or whose
    /// priority names no value, or an `Error` whose code names none, is
    /// refused by `from_cbor`, a later op of the batch too; and a message of
    /// another shape (not a map, a field missing, a field of another type)
    /// is refused too, where the legacy `from_cbor` panicked. Their
    /// neighbours, a crdt op at bulk priority and the last error code,
    /// decode.
    #[test]
    fn a_message_holding_an_unknown_value_or_another_shape_is_refused() {
        let unknown =
            |enum_name: &'static str, value: i64| DecodeError::UnknownEnum { enum_name, value };
        let op = |shape| with(Op::default().to_cbor(), 9, shape);
        let ops = |ops: Vec<Cbor>, pri| Cbor::Map(vec![(1, Cbor::Array(ops)), (2, pri)]);
        let refused = [
            (ops(vec![op(9)], Cbor::Null), unknown("Shape", 9)),
            (ops(vec![op(0), op(-1)], Cbor::Null), unknown("Shape", -1)),
            (ops(vec![op(4)], Cbor::Int(3)), unknown("Priority", 3)),
            (Cbor::Int(3), DecodeError::WrongType { expected: "map" }),
            (Cbor::Map(vec![]), DecodeError::MissingKey(1)),
            (
                Cbor::Map(vec![(1, Cbor::Int(1))]),
                DecodeError::WrongType { expected: "array" },
            ),
        ];
        for (body, why) in refused {
            assert_eq!(Ops::from_cbor(&body), Err(why), "{body:?}");
        }
        let named = Ops::from_cbor(&ops(vec![op(4), op(0)], Cbor::Int(2))).unwrap();
        assert_eq!(
            (named.ops[0].shape, named.pri),
            (Shape::Crdt, Some(Priority::Bulk))
        );

        let error = |code| with(Error::default().to_cbor(), 1, code);
        assert_eq!(Error::from_cbor(&error(7)), Err(unknown("ErrorCode", 7)));
        assert_eq!(
            Error::from_cbor(&error(6)).unwrap().code,
            ErrorCode::Internal
        );
    }
}
