//! Glade wire codec (GLP-0005, P0.S4): IR-driven CBOR codec over generated
//! native structs for the glade framing protocol (`taut/ir/glade.taut.py`).
//!
//! `cbor.rs` and `generated.rs` are REGENERATED by
//! `python -m taut.corpus.glade_build` — do not edit them by hand. The
//! conformance tests below prove this crate reproduces taut's Python-authored
//! golden corpus byte-for-byte; parity == correctness, and the same corpus
//! pins the TypeScript codec (browser-folds premise).

pub mod cbor;
pub mod generated;

#[cfg(test)]
mod codec_tests {
    use crate::cbor;
    use crate::generated::{self, Op, Shape, VECTORS};

    fn hex_to_bytes(h: &str) -> Vec<u8> {
        (0..h.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&h[i..i + 2], 16).unwrap())
            .collect()
    }
    fn bytes_to_hex(b: &[u8]) -> String {
        b.iter().map(|x| format!("{:02x}", x)).collect()
    }

    /// The CBOR substrate alone round-trips every vector (decode->encode).
    #[test]
    fn cbor_substrate_roundtrips_corpus() {
        for (name, _msg, hex) in VECTORS {
            let re = bytes_to_hex(&cbor::encode(&cbor::decode(&hex_to_bytes(hex))));
            assert_eq!(&re, hex, "cbor substrate mismatch for {}", name);
        }
    }

    /// The IR codec reproduces every golden vector byte-for-byte via the typed
    /// structs: bytes -> native struct -> bytes.
    #[test]
    fn ir_codec_reproduces_corpus_byte_for_byte() {
        assert!(!VECTORS.is_empty(), "no vectors generated");
        for (name, message, hex) in VECTORS {
            let re = bytes_to_hex(&generated::roundtrip(message, &hex_to_bytes(hex)));
            assert_eq!(&re, hex, "IR codec mismatch for {}", name);
        }
    }

    /// Spot-check a typed decode: the op envelope's identity + fold fields.
    #[test]
    fn op_envelope_decodes_typed() {
        let entry = VECTORS.iter().find(|(n, _, _)| *n == "edge/op-chain").unwrap();
        let op = Op::from_cbor(&cbor::decode(&hex_to_bytes(entry.2)));
        assert_eq!(op.seq, 5);
        assert_eq!(op.prev.as_ref().unwrap().len(), 32); // per-origin chain hash (GQ-9)
        assert_eq!(op.shape, Shape::Log);
        assert!(!op.refs.is_empty()); // causal refs
    }
}
